import { PrismaClient } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';

dotenv.config();

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function generate() {
  console.log('Generating Dictionary Enums...');

  const items = await prisma.dictionary.findMany({
    orderBy: { id: 'asc' },
  });

  const grouped: Record<string, { key: string; id: number }[]> = {};

  for (const item of items) {
    if (!grouped[item.type]) grouped[item.type] = [];
    grouped[item.type].push({ key: item.key, id: item.id });
  }

  let fileContent = `// AUTO-GENERATED FILE - DO NOT EDIT\n// Generated by scripts/generate-dictionary-enums.ts\n\n`;

  for (const [type, entries] of Object.entries(grouped)) {
    // Capitalize type e.g. "MATERIAL" -> "MaterialDict"
    const enumName = type.charAt(0).toUpperCase() + type.slice(1).toLowerCase() + 'Dict';

    fileContent += `export enum ${enumName} {\n`;
    for (const entry of entries) {
      // Ensure the key is a valid TS identifier
      const safeKey = entry.key.replace(/[^a-zA-Z0-9_]/g, '');
      if (safeKey.match(/^[0-9]/)) {
        fileContent += `  _${safeKey} = ${entry.id},\n`;
      } else {
        fileContent += `  ${safeKey} = ${entry.id},\n`;
      }
    }
    fileContent += `}\n\n`;
  }

  const outPath = path.join(__dirname, '../src/dictionary/generated-dictionary.ts');
  
  // Create dir if not exists
  const dir = path.dirname(outPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outPath, fileContent, 'utf8');
  console.log(`Generated enums at ${outPath}`);
}

generate()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
